In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
# 1. 1-D array like object containint an array
df = pd.Series([4, 5, 2, 8])
df

0    4
1    5
2    2
3    8
dtype: int64

In [7]:
# 2. Convert series to list and print its type
lst = list(df)
lst

[4, 5, 2, 8]

In [8]:
type(lst)

list

In [14]:
# 3. Add, subtract, multiple, divide series
s1 = pd.Series([2, 4, 6, 8, 10])
s2 = pd.Series([1, 3, 5, 7, 9])

In [10]:
s1 - s2

0    1
1    1
2    1
3    1
4    1
dtype: int64

In [11]:
s1 + s2

0     3
1     7
2    11
3    15
4    19
dtype: int64

In [12]:
s1 * s2

0     2
1    12
2    30
3    56
4    90
dtype: int64

In [13]:
s1 / s2

0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64

In [15]:
# 4. compare 2 series
s1 > s2

0    True
1    True
2    True
3    True
4    True
dtype: bool

In [17]:
s1.compare(s2)

self  other
0     2      1
1     4      3
2     6      5
3     8      7
4    10      9

In [18]:
# 5. convert dictionary to series
d1 = {'a': 100, 'b': 200, 'c': 300, 'd': 400, 'e': 800}
d1

{'a': 100, 'b': 200, 'c': 300, 'd': 400, 'e': 800}

In [19]:
pd.Series(d1)

a    100
b    200
c    300
d    400
e    800
dtype: int64

In [20]:
# 6. numpy array to series
n = np.array([10, 20, 30, 40, 50])
n

array([10, 20, 30, 40, 50])

In [21]:
pd.Series(n)

0    10
1    20
2    30
3    40
4    50
dtype: int32

In [23]:
# 7. change datatype of index
a = pd.Series([100, 200, 'python', 300.12, 400] )

In [24]:
a

0       100
1       200
2    python
3    300.12
4       400
dtype: object

In [35]:
a = pd.Series([100, 200, 'python', 300.12, 400])
# If ‘coerce’, then invalid parsing will be set as NaN.
pd.to_numeric(a, errors='coerce')

0    100.00
1    200.00
2       NaN
3    300.12
4    400.00
dtype: float64

In [43]:
# 8. 1st column of DataFrame to a series
d1 = {'col1': [1, 2, 3, 4, 7, 11], 'col2': [4, 5, 6, 9, 5, 0], 'col3': [7, 5, 8, 12, 1, 11]}
df = pd.DataFrame(d1)
df

col1  col2  col3
0     1     4     7
1     2     5     5
2     3     6     8
3     4     9    12
4     7     5     1
5    11     0    11

In [48]:
(df['col1'])

0     1
1     2
2     3
3     4
4     7
5    11
Name: col1, dtype: int64

In [49]:
# 9. series to an array
s1 = pd.Series([4, 5, 11, 22, 9])
s1

0     4
1     5
2    11
3    22
4     9
dtype: int64

In [50]:
np.array(s1)

array([ 4,  5, 11, 22,  9], dtype=int64)

In [56]:
# 10. series of list to one list
s = pd.Series([['red', 'green', 'white'],['red', 'black'],['pink']])
ser = s.apply(pd.Series).stack().reset_index(drop=True)
ser

0      red
1    green
2    white
3      red
4    black
5     pink
dtype: object

In [64]:
# 11.Pandas program to sort a given Series
s1 = pd.Series(['100','200','python','300.12','400'])
s2 = pd.Series(s1).sort_values()
s2

0       100
1       200
3    300.12
4       400
2    python
dtype: object

In [70]:
# 12. Write a Pandas program to add some data to an existing Series.
s1 = pd.Series(['100','200','python','300.12','400'])
s2 = pd.Series(['500','php'])
snew = pd.concat([s1,s2],ignore_index=True)
snew

0       100
1       200
2    python
3    300.12
4       400
5       500
6       php
dtype: object

In [75]:
# 13.Write a Pandas program to create a subset of a given series based on value and condition.
a = np.arange(0,11)
a
s1 = pd.Series(a)
s1

0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
dtype: int32

In [76]:
s1[s1<6]

0    0
1    1
2    2
3    3
4    4
5    5
dtype: int32

In [79]:
# 14. Write a pandas program to change the order of the index of a given series.
s1 = pd.Series(data=[1,2,3,4,5],index=['A','B','C','D','E'])
s1

A    1
B    2
C    3
D    4
E    5
dtype: int64

In [80]:
s1 = s1.reindex(index=['B','A','C','D','E'])
s1

B    2
A    1
C    3
D    4
E    5
dtype: int64

In [81]:
# 15. Write a Pandas program to create the mean and standard deviation of the data of a given Series.
s1 = pd.Series([1,2,3,4,5,6,7,8,9,5,3])
s1

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9     5
10    3
dtype: int64

In [83]:
print("Mean of the said Data Series: ")
s1.mean()

Mean of the said Data Series: 


4.818181818181818

In [84]:
print("Standard deviation of the said Data Series: ")
s1.std()

Standard deviation of the said Data Series: 


2.522624895547565

In [85]:
# 16.Write a Pandas program to get the items of a given series not present in another given series.
s1 = pd.Series([1,2,3,4,5])
s1

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [99]:
s2 = pd.Series([2,4,6,8,10])
s2

0     2
1     4
2     6
3     8
4    10
dtype: int64

In [100]:
s1[~s1.isin(s2)]

0    1
2    3
4    5
dtype: int64

In [106]:
# 17.Write a Pandas program to get the items which are not common of two given series.
s1 = pd.Series([1,2,3,4,5])
s2 = pd.Series([2,4,6,8,10])
s1 = pd.Series(np.union1d(s1,s2))
s2 = pd.Series(np.intersect1d(s1,s2))
result = s1[~s1.isin(s2)]
result

0    1
2    3
4    5
dtype: int64

In [113]:
# 18. program to compute the minimum, 25th percentile, median, 75th, and maximum of a given series.
s1 = np.random.RandomState(100)
s1 = pd.Series(s1.normal(10,4,20))
s1

0      3.000938
1     11.370722
2     14.612143
3      8.990256
4     13.925283
5     12.056875
6     10.884719
7      5.719827
8      9.242017
9     11.020006
10     8.167892
11    11.740654
12     7.665620
13    13.267388
14    12.690883
15     9.582355
16     7.874878
17    14.118931
18     8.247458
19     5.526727
dtype: float64

In [115]:
result = np.percentile(s1,q=[0,25,50,75,100])
result

array([ 3.00093811,  8.09463867, 10.23353705, 12.21537733, 14.61214321])

In [130]:
# 19.Write a Pandas program to calculate the frequency counts of each unique value of a given series.
s1 = pd.Series(np.take(list('0123456789'),np.random.randint(10,size=40)))
s1
res = s1.value_counts()
res

9    9
4    7
6    6
3    5
7    4
0    3
8    2
1    2
2    1
5    1
Name: count, dtype: int64

In [131]:
# 20. display most frequent, and replace everything else with 'Other'
s1.mode()

0    9
dtype: object

In [134]:
freq = s1.mode()[0]
res = s1.where(s1 == freq, 'Other')
# 3res

0     Other
1     Other
2         9
3     Other
4     Other
5     Other
6     Other
7         9
8     Other
9     Other
10    Other
11        9
12    Other
13        9
14    Other
15    Other
16    Other
17    Other
18        9
19        9
20    Other
21    Other
22        9
23    Other
24    Other
25        9
26    Other
27    Other
28    Other
29    Other
30    Other
31    Other
32        9
33    Other
34    Other
35    Other
36    Other
37    Other
38    Other
39    Other
dtype: object

In [137]:
# 21. posistion of numbers that are multiple of 5
s1 = pd.Series([1, 9, 8, 6, 95, 7, 105, 1, 10])
s1[s1%5==0]

4     95
6    105
8     10
dtype: int64

In [141]:
# 22. extract items at a given position of a series
s1 = pd.Series([4, 5, 7, 9, 10, 44])
s1[2]

7

In [142]:
# 23. to get positions of a given series
s1 = pd.Series([1,2,3,4,5,6,7,8,9,10])
s1

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64

In [140]:
s2 = pd.Series([1,3,5,7,10])
s2

0     1
1     3
2     5
3     7
4    10
dtype: int64

In [145]:
 # 24. convert 1st and last character of each word to upper case in each word 
s1 = pd.Series(['php', 'python', 'java', 'c#'])
res = s1.map(lambda x: x[0].upper() + x[1:-1] + x[-1].upper())
res

0       PhP
1    PythoN
2      JavA
3        C#
dtype: object

In [147]:
# 25.Write a Pandas program to calculate the number of characters in each word in a given series.
s1 = pd.Series(['php', 'python', 'java', 'c#'])
s1.map(lambda x: len(x))

0    3
1    6
2    4
3    2
dtype: int64

In [150]:
# 26.Write a Pandas program to compute difference of differences between consecutive numbers of a given series.
s1 = pd.Series([1,3,5,8,10,11,15])
s2 = s1.diff()
s2

0    NaN
1    2.0
2    2.0
3    3.0
4    2.0
5    1.0
6    4.0
dtype: float64

In [151]:
s2.diff()

0    NaN
1    NaN
2    0.0
3    1.0
4   -1.0
5   -1.0
6    3.0
dtype: float64

In [153]:
# 27. Write a Pandas program to convert a series of date strings to a timeseries.
s1 = pd.Series(['01 Jan 2015','10-02-2016','20180307','2014/05/06','2016-04-12','2019-04-06T11:20'])
s1

0         01 Jan 2015
1          10-02-2016
2            20180307
3          2014/05/06
4          2016-04-12
5    2019-04-06T11:20
dtype: object

In [157]:
# pd.to_datetime(s1)

In [182]:
# 28.Write a Pandas program to get the day of month, day of year, week number and day of week from a given series of date strings.
from dateutil.parser import parse
import datetime

s1 = pd.Series(['01 Jan 2015','10-02-2016','20180307','2014/05/06','2016-04-12','2019-04-06T11:20'])
s1

0         01 Jan 2015
1          10-02-2016
2            20180307
3          2014/05/06
4          2016-04-12
5    2019-04-06T11:20
dtype: object

In [191]:
s1 = pd.to_datetime(s1,format='mixed')
s1

0   2015-01-01 00:00:00
1   2016-10-02 00:00:00
2   2018-03-07 00:00:00
3   2014-05-06 00:00:00
4   2016-04-12 00:00:00
5   2019-04-06 11:20:00
dtype: datetime64[ns]

In [192]:
s1.dt.day

0     1
1     2
2     7
3     6
4    12
5     6
dtype: int32

In [193]:
s1.dt.month

0     1
1    10
2     3
3     5
4     4
5     4
dtype: int32

In [194]:
s1.dt.year

0    2015
1    2016
2    2018
3    2014
4    2016
5    2019
dtype: int32

In [197]:
# 29. Write a Pandas program to convert year-month string to dates adding a specified day of the month.
s1 = pd.Series(['Jan 2015','Feb 2016','Mar 2017','Apr 2018','May 2019'])
s1

0    Jan 2015
1    Feb 2016
2    Mar 2017
3    Apr 2018
4    May 2019
dtype: object

In [200]:
res = s1.map(lambda d:parse('11'+d))
res

0   2015-01-11
1   2016-02-11
2   2017-03-11
3   2018-04-11
4   2019-05-11
dtype: datetime64[ns]

In [206]:
# 30. Write a Pandas program to filter words from a given series that contain atleast two vowels.
s1 = pd.Series(['Red','Green','Orange','Pink','Yellow','White'])
s1

0       Red
1     Green
2    Orange
3      Pink
4    Yellow
5     White
dtype: object

In [209]:
# res = s1.map(lambda c: sum([Counter(c.lower()).get(i,0)for i in list('aeiou')])>=2)    


In [214]:
# 31. Write a Pandas program to compute the Euclidean distance between two given series.
n1 = np.arange(1,11)
s1 = pd.Series(n1)
s2 = pd.Series([11,8,7,5,6,5,3,4,7,1])
np.linalg.norm(s1-s2)

16.492422502470642

In [216]:
# 32. Write a Pandas program to find the positions of the values neighboured by smaller values on both sides in a given series.
s1 = pd.Series([1,8,7,5,6,5,3,4,7,1])
s1

0    1
1    8
2    7
3    5
4    6
5    5
6    3
7    4
8    7
9    1
dtype: int64

In [219]:
temp = np.diff(np.sign(np.diff(s1)))
res = np.where(temp==-2)[0]+1
res

array([1, 4, 8], dtype=int64)

In [220]:
# 33. Write a Pandas program to replace missing white spaces in a given string with the least frequent character.
s1 = 'abc def abcdef icd'
s1

'abc def abcdef icd'

In [222]:
ser = pd.Series(list(s1))
ser

0     a
1     b
2     c
3      
4     d
5     e
6     f
7      
8     a
9     b
10    c
11    d
12    e
13    f
14     
15    i
16    c
17    d
dtype: object

In [224]:
element_freq = ser.value_counts()
element_freq

c    3
     3
d    3
a    2
b    2
e    2
f    2
i    1
Name: count, dtype: int64

In [225]:
current_freq = element_freq.dropna().index[-1]
result = "".join(ser.replace(' ',current_freq))
result

'abcidefiabcdefiicd'

In [226]:
# 34. Write a Pandas program to compute the autocorrelations of a given numeric series.
s1 = pd.Series(np.arange(15)+np.random.normal(1,10,15))
s1

0      6.282386
1     13.145129
2      1.042370
3      2.406047
4      4.772776
5      0.097318
6     11.382632
7      2.025045
8     12.656032
9     20.071962
10    14.163085
11    16.947623
12     5.824107
13     0.243504
14    28.294236
dtype: float64

In [227]:
auto = [s1.autocorr(i).round(2) for i in range(11)]
auto[1:]

[-0.01, 0.04, 0.22, -0.25, 0.42, -0.04, -0.43, 0.72, -0.2, 0.45]

In [229]:
# 35. Write a Pandas program to create a TimeSeries to display all the Sundays of given year.
result = pd.Series(pd.date_range('2020-01-01', periods=52, freq='W-SUN'))
print("All Sundays of 2019:")
result

All Sundays of 2019:


0    2020-01-05
1    2020-01-12
2    2020-01-19
3    2020-01-26
4    2020-02-02
5    2020-02-09
6    2020-02-16
7    2020-02-23
8    2020-03-01
9    2020-03-08
10   2020-03-15
11   2020-03-22
12   2020-03-29
13   2020-04-05
14   2020-04-12
15   2020-04-19
16   2020-04-26
17   2020-05-03
18   2020-05-10
19   2020-05-17
20   2020-05-24
21   2020-05-31
22   2020-06-07
23   2020-06-14
24   2020-06-21
25   2020-06-28
26   2020-07-05
27   2020-07-12
28   2020-07-19
29   2020-07-26
30   2020-08-02
31   2020-08-09
32   2020-08-16
33   2020-08-23
34   2020-08-30
35   2020-09-06
36   2020-09-13
37   2020-09-20
38   2020-09-27
39   2020-10-04
40   2020-10-11
41   2020-10-18
42   2020-10-25
43   2020-11-01
44   2020-11-08
45   2020-11-15
46   2020-11-22
47   2020-11-29
48   2020-12-06
49   2020-12-13
50   2020-12-20
51   2020-12-27
dtype: datetime64[ns]

In [230]:
# 36. Write a Pandas program to convert given series into a dataframe with its index as another column on the dataframe
char_list = list('ABCDEFGHIJKLMNOP')
num_arra = np.arange(8)
num_dict = dict(zip(char_list, num_arra))
num_ser = pd.Series(num_dict)
df = num_ser.to_frame().reset_index()
df

index  0
0     A  0
1     B  1
2     C  2
3     D  3
4     E  4
5     F  5
6     G  6
7     H  7

In [235]:
# 37.Write a Pandas program to stack two given series vertically and horizontally.
s1 = pd.Series(range(10))
s2 = pd.Series(list('pqrstuvwxy'))
print("Original Series:")
s1

Original Series:


0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64

In [238]:
df = pd.concat([s1, s2], axis=1)
print("\nStack two given series vertically and horizontally:")
df


Stack two given series vertically and horizontally:


0  1
0  0  p
1  1  q
2  2  r
3  3  s
4  4  t
5  5  u
6  6  v
7  7  w
8  8  x
9  9  y

In [239]:
# 38. Write a Pandas program to check the equality of two given series.
nums1 = pd.Series([1, 8, 7, 5, 6, 5, 3, 4, 7, 1])
nums2 = pd.Series([1, 8, 7, 5, 6, 5, 3, 4, 7, 1])
print("Original Series:")
nums1


Original Series:


0    1
1    8
2    7
3    5
4    6
5    5
6    3
7    4
8    7
9    1
dtype: int64

In [241]:
nums2


0    1
1    8
2    7
3    5
4    6
5    5
6    3
7    4
8    7
9    1
dtype: int64

In [242]:
print("Check 2 series are equal or not?")
nums1 == nums2

Check 2 series are equal or not?


0    True
1    True
2    True
3    True
4    True
5    True
6    True
7    True
8    True
9    True
dtype: bool

In [243]:
# 39.Write a Pandas program to find the index of the first occurrence of the smallest and largest value of a given series.
nums = pd.Series([1, 3, 7, 12, 88, 23, 3, 1, 9, 0])
print("Original Series:")
nums


Original Series:


0     1
1     3
2     7
3    12
4    88
5    23
6     3
7     1
8     9
9     0
dtype: int64

In [246]:
print("Index of the first occurrence of the smallest value of the said series:")
nums.idxmin()


Index of the first occurrence of the smallest value of the said series:


9

In [248]:
print("Index of the first occurrence of the largest value of the said series:")
nums.idxmax()

Index of the first occurrence of the largest value of the said series:


4

In [ ]:
# 40.Write a Pandas program to check inequality over the index axis of a given dataframe and a given series
