In [1]:
import numpy as np
import pandas as pd

In [2]:
#1.Write a NumPy program to get the numpy version and show numpy build configuration.
np.__version__

'1.26.4'

In [5]:
np.show_config

<function numpy.__config__.show(mode='stdout')>

In [7]:
# 2. Write a NumPy program to get help on the add function.   
a = np.array([1,2,3])
b = np.array([4,5,6])
a+b

array([5, 7, 9])

In [9]:
# 3. Write a NumPy program to test whether none of the elements of a given array is zero.
arr = np.array([1,2,3,0,6,0,1,-1])
arr[arr!=0]

array([ 1,  2,  3,  6,  1, -1])

In [11]:
#4. Write a NumPy program to test whether any of the elements of a given array is non-zero.   
arr = np.array([0,2,3,5,6,0])
arr[arr!=0]

array([2, 3, 5, 6])

In [13]:
# 5. Write a NumPy program to test a given array element-wise for finiteness (not infinity or not a Number).   
arr = np.array([2,4,5,6,7777777777777777,0])
np.isfinite(arr)

array([ True,  True,  True,  True,  True,  True])

In [15]:
# 6. Write a NumPy program to test element-wise for positive or negative infinity.  
arr = np.array([2,4,5,6,7777777777777777,0])
np.isneginf(-np.inf)

True

In [17]:
np.isposinf(np.inf)

True

In [19]:
# 7. Write a NumPy program to test element-wise for NaN of a given array.  
arr = np.array([1,4,5,6,0])
np.isnan(arr)

array([False, False, False, False, False])

In [21]:
# 8. Write a NumPy program to test element-wise for complex number, real number of a given array. 
# Also test whether a given number is a scalar type or not.   
arr = np.array([1+4j,2+5j,6])
np.iscomplex(arr)

array([ True,  True, False])

In [23]:
np.isreal(arr)

array([False, False,  True])

In [25]:
# 9. Write a NumPy program to create an element-wise comparison (greater, greater_equal, less and 
#less_equal) of two given arrays.  
arr = np.array([1,2,3,4,5,6,7,8,9])
arr[arr>5]

array([6, 7, 8, 9])

In [27]:
arr[arr<3]

array([1, 2])

In [29]:
arr[arr>=5]

array([5, 6, 7, 8, 9])

In [31]:
arr[arr<=3]

array([1, 2, 3])

In [33]:
# 10. Write a NumPy program to create an array with the values 1, 7, 13, 105 and determine the size of the 
#memory occupied by the array. 
arr = np.array([1,7,13,105])
arr.nbytes

16

In [35]:
# 11. Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives.   
arr1 = np.zeros(10)
arr1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [37]:
arr2 = np.ones(10)
arr2

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [39]:
arr3 = arr2*5
arr3

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [41]:
# 12. Write a NumPy program to create an array of the integers from 30 to70.
arr = np.arange(30,71)
arr

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
       64, 65, 66, 67, 68, 69, 70])

In [43]:
# 13. Write a NumPy program to create an array of all the even integers from 30 to 70. 
arr[arr%2==0]

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62,
       64, 66, 68, 70])

In [45]:
# 14. Write a NumPy program to create a 3x3 identity matrix.   
id = np.identity(3)
id

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [47]:
# 15. Write a NumPy program to generate a random number between 0 and 1.
ar1 = np.random.randint(0,1)
ar1

0

In [49]:
# 16. Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution.  
arr = np.random.randint(15,size=15)
arr

array([10,  2,  5,  3,  9,  9,  1,  7,  5,  3, 12,  1,  0,  1,  7])

In [51]:
# 17.  Write a NumPy program to create a vector with values ranging from 15 to 55 and print 
#all values except the first and last.  
arr = np.arange(15,56)
arr[1:-1]

array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
       33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
       50, 51, 52, 53, 54])

In [53]:
# 18.  Write a NumPy program to create a 3X4 array. 
arr = np.random.randint(12,size=(3,4))
arr

array([[5, 2, 2, 9],
       [7, 0, 9, 4],
       [2, 5, 2, 8]])

In [55]:
# 19.  Write a NumPy program to create a vector of length 10 with values evenly distributed                    
#between 5 and 50.  
arr = np.linspace(5,50,10)
arr

array([ 5., 10., 15., 20., 25., 30., 35., 40., 45., 50.])

In [57]:
# 20.Write a NumPy program to create a vector with values from 0 to 20 and change the sign of the 
#numbers in the range from 9 to 15.  
arr = np.arange(0,21)
arr[9:16] = -arr[9:16]
arr

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,  -9, -10, -11, -12,
       -13, -14, -15,  16,  17,  18,  19,  20])

In [59]:
# 21.Write a NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 10. 
arr = np.random.randint(0,10,size=5)
arr

array([8, 4, 0, 8, 4])

In [61]:
# 22. Write a NumPy program to multiply the values of two given vectors.   
ar1 = np.array([1,2,3,4,6])
ar2 = np.array([4,3,2,5,6])
ar1*ar2

array([ 4,  6,  6, 20, 36])

In [63]:
# 23. Write a NumPy program to create a 3x4 matrix filled with values from 10 to 21. 
arr = np.random.randint(10,21,size=(3,4))
arr

array([[15, 12, 17, 13],
       [19, 13, 13, 12],
       [18, 14, 18, 15]])

In [65]:
# 24. Write a NumPy program to find the number of rows and columns of a given matrix.  
rows , columns = arr.shape
rows

3

In [67]:
columns

4

In [69]:
# 25. Write a NumPy program to create a 3x3 identity matrix, i.e. diagonal elements are 1, the rest are 0. 
arr = np.identity(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [71]:
#26. Write a NumPy program to create a 10x10 matrix, in which the elements on the borders will be 
#equal to 1, and inside 0.   
arr = np.ones((10,10))
arr

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [73]:
arr[1:-1, 1:-1] = 0
arr

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [75]:
# 27. Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal 
#equal to 1, 2, 3, 4, 5.   
arr = np.zeros((5,5))
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [77]:
np.fill_diagonal(arr,[1,2,3,4,5])

In [79]:
arr

array([[1., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 4., 0.],
       [0., 0., 0., 0., 5.]])

In [81]:
# 28. Write a NumPy program to create a 3x3x3 array filled with arbitrary values. 
arr = np.random.randint(45,size=(3,3,3))
arr

array([[[32,  1, 20],
        [40, 23, 34],
        [18,  6, 44]],

       [[11, 17, 23],
        [ 7,  8, 10],
        [ 7, 36, 25]],

       [[24,  5, 24],
        [36, 39, 27],
        [33, 35, 23]]])

In [83]:
# 29.  Write a NumPy program to compute the inner product of two given vectors.  
a1 = np.array([2,3,4,1])
a2 = np.array([3,5,6,7])
np.inner(a1,a2)

52

In [85]:
#30. Write a NumPy program to sort a given array by row and column in ascending order.   
arr = np.array([[2,3,4,1],[3,5,6,7]])
np.sort(arr,axis=0)

array([[2, 3, 4, 1],
       [3, 5, 6, 7]])

In [87]:
np.sort(arr,axis=1)

array([[1, 2, 3, 4],
       [3, 5, 6, 7]])

In [89]:
# 31.  Write a NumPy program to extract all numbers from a given array which are less and greater 
# than a specified number.   
arr = np.array([1,2,3,5,6,4,7,8,9])
arr[arr>5]

array([6, 7, 8, 9])

In [91]:
arr[arr<5]

array([1, 2, 3, 4])

In [95]:
#32.  Write a NumPy program to replace all numbers in a given array which is equal, 
# less and greater to a given number. 
arr = np.array([1,2,7,3,4,7,5,6,5,6,7,7,37,7,8,9,10])

In [97]:
arr[arr==7]

array([7, 7, 7, 7, 7])

In [99]:
arr[arr>7]

array([37,  8,  9, 10])

In [101]:
arr[arr<7]

array([1, 2, 3, 4, 5, 6, 5, 6])

In [107]:
# 33. Write a NumPy program to create an array of equal shape and data type of a given array.
nums = np.array([[34,12,67,54],[34,57,23,45],[89,43,12,56]])
np.ones_like(nums)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [113]:
# 34. Write a NumPy program to create a three-dimension array with shape (3,5,4) and set to a
# variable.
arr = np.random.randint(34,size=(3,5,4))
arr

array([[[ 3, 22, 10,  0],
        [11, 32, 20, 30],
        [21,  2, 18, 18],
        [14, 29, 14, 30],
        [ 7, 15,  4, 22]],

       [[10, 31,  5,  7],
        [ 2, 27, 29, 17],
        [ 9,  7, 11, 28],
        [ 2,  7, 17, 17],
        [23,  3,  4, 15]],

       [[26, 11, 19, 30],
        [29, 12,  6, 14],
        [ 5, 19, 28, 25],
        [21, 24, 19,  3],
        [30, 28, 19,  1]]])

In [117]:
# 35. Write a NumPy program to multiply two given arrays of same size element-by-element.
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
a*b

array([ 5, 12, 21, 32])