In [1]:
import numpy as np

In [3]:
arr = np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
# Basic arithmetic
arr+arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [7]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [9]:
arr*arr

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [19]:
# This will raise a Warning on division by zero, but not an error!
# It just fills the spot with nan
arr/arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [21]:
# Also a warning (but not an error) relating to infinity
1/arr

array([1.        , 0.5       , 0.33333333, 0.25      , 0.2       ,
       0.16666667, 0.14285714, 0.125     , 0.11111111])

In [15]:
arr**3

array([  1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [23]:
# Universal functions
# Taking Square Roots
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        ])

In [25]:
# Calculating exponential (e^)
np.exp(arr)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

In [27]:
# Trigonometric Functions like sine
np.sin(arr)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [29]:
# Taking the Natural Logarithm
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [31]:
arr.sum()

45

In [33]:
arr.mean()

5.0

In [35]:
arr.max()

9

In [37]:
arr.min()

1

In [39]:
arr.var()

6.666666666666667

In [41]:
arr.std()

2.581988897471611

In [43]:
# 2D arrays
# This is a 2-dimensional array with 3 rows and 4 columns
arr_2d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [55]:
# Sum all the columns for each row (e.g. 1+5+9, 2+6+10, etc)
arr_2d.sum(axis=0)

array([15, 18, 21, 24])

In [59]:
# Row and column count
arr_2d.shape

(3, 4)

In [61]:
# Sum all the rows for each column (e.g. 1+2+3+4, 5+6+7+8, etc)
arr_2d.sum(axis=1)

array([10, 26, 42])