In [1]:
import numpy as np

In [3]:
#Creating sample array
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
# Bracket indexing and selection - similar to Python lists
#Get a value at an index
arr[8]

8

In [9]:
#Get values in a range
arr[1:5]

array([1, 2, 3, 4])

In [11]:
#Get values in a range
arr[0:4]

array([0, 1, 2, 3])

In [15]:
# Broadcasting
#Setting a value with index range (Broadcasting)
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [17]:
# Reset array, why? will be clear soon
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
#Important notes on Slices
slice_of_arr = arr[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [25]:
# change slice
slice_of_arr[:]=99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [29]:
arr
# Changes made are also there in our original array!
# Data is not copied, it is a view of the original array! 
# This avoids memory problems

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [31]:
#To get a copy, we need to be explicit
arr_copy = arr.copy()
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [39]:
# 2D arrays
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
#Indexing row
arr_2d[1]

array([4, 5, 6])

In [43]:
# Getting individual element value
# Syntax is arr_2d[row][col] or arr_2d[row,col]
arr_2d[0][1]

2

In [49]:
arr_2d[2,2]

9

In [51]:
# 2D array slicing
# Shape (2,2) from top right corner
arr_2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [53]:
# Shape bottom row
arr_2d[2]

array([7, 8, 9])

In [55]:
arr_2d[2,:]

array([7, 8, 9])

In [57]:
# conditional selection
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [59]:
# Check each element of the array  against the condition arr > 4, 
#  which returns a boolean array where 
#  each element is True if the corresponding element in arr is greater than 4, 
#  and False otherwise
arr>4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [61]:
# Store boolean results in another array
bool_arr = arr>4
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [63]:
# Select only those elements from the arr array where 
# the corresponding element in bool_arr is True
# It effectively filters out the elements of arr where the condition arr > 4 is True
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [65]:
'''
arr > 2 creates a boolean array where each element is True if 
the corresponding element in arr is greater than 2, and False otherwise

arr[arr > 2] uses this boolean array as a mask to select only the elements 
of arr where the corresponding element in the boolean array is True

The array arr is [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
The boolean array arr > 2 is [False False True True True True True True True True].
So, arr[arr > 2] selects only those elements of arr where the corresponding 
element in the boolean array is True, 
which are [3, 4, 5, 6, 7, 8, 9, 10]
'''
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [67]:
# Same as before
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])