In [1]:
import numpy as np

In [2]:
# making an numpy array from the list of data type integer
myarr = np.array([1,2,3,4],np.int8)
myarr

array([1, 2, 3, 4], dtype=int8)

In [3]:
myarr[1]

2

In [4]:
# making the 2D array from the list
myarr1 = np.array([[1,2,3,4]],np.int8)
myarr1

array([[1, 2, 3, 4]], dtype=int8)

In [5]:
myarr1[0,1]

2

In [6]:
# to find shape of array
myarr.shape

(4,)

In [7]:
# to find shape of array
myarr1.shape

(1, 4)

In [8]:
# to find datatype of array
myarr.dtype

dtype('int8')

In [9]:
# to modify the value in an array
myarr1[0,1] = 45
myarr1

array([[ 1, 45,  3,  4]], dtype=int8)

In [10]:
# to create an array from the 
listarray = np.array([[1,2,3],[4,5,6],[7,8,9]])
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
listarray.dtype

dtype('int32')

In [12]:
listarray.shape

(3, 3)

In [13]:
listarray.size

9

In [14]:
np.array({34,35,67})

array({35, 34, 67}, dtype=object)

In [15]:
# to create an numpy array of zeros with 2 rows and 5 columns
zeros = np.zeros((2,5))
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
zeros.dtype

dtype('float64')

In [17]:
zeros.shape

(2, 5)

In [18]:
# gives you numpy array using the arange function
rang = np.arange(15)
rang

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [19]:
# linspace returns 12 numbers in 1 to 5 it decides on its own how much space should be there betweeen any th0 numbers because we decide only how much number we want to print
lspace = np.linspace(1,5,12)
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [20]:
# It returns an empty array of (4,6) and gives random values in it we can assign the values to it 
emp = np.empty((4,6))
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.11261027e-306, 7.56587585e-307, 1.37961302e-306],
       [1.05699242e-307, 8.01097889e-307, 1.78020169e-306,
        7.56601165e-307, 1.02359984e-306, 1.33510679e-306],
       [2.22522597e-306, 8.01097889e-307, 1.42417629e-306,
        8.45593934e-307, 6.89805151e-307, 1.42421160e-306],
       [1.06810268e-306, 8.34448108e-308, 1.78022342e-306,
        8.06635958e-308, 8.34423917e-308, 2.10081501e-312]])

In [21]:
# here it returns an array of size which we passed to empty_like function,it gives the random numbers and we can modify this values 
emp_like = np.empty_like(lspace)
emp_like

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [22]:
# To print the identity matrix of size (4,4)
ide = np.identity(4)
ide

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [23]:
ide.shape

(4, 4)

In [24]:
arr2 = np.arange(99)
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [25]:
arr2.shape

(99,)

In [26]:
# To reshape already existing array
arr3 = arr2.reshape(3,33)
arr3

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [27]:
arr3.shape

(3, 33)

In [28]:
# To create 1D array out of any array
arr3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [29]:
arr3.shape

(3, 33)

In [30]:
x = [[1,2,3],[4,5,6],[7,8,9]]
x

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [31]:
ar = np.array(x)
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
# Sum of all elements in an array
ar.sum()

45

In [33]:
# sum of column elements of an array
ar.sum(axis=0)

array([12, 15, 18])

In [34]:
# sum of row elements of an array
ar.sum(axis=1)

array([ 6, 15, 24])

In [35]:
# Transpose of an array
ar.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [36]:
# here you get an iterator
ar.flat

In [37]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
8
9


In [38]:
# gives number of dimensions
ar.ndim

2

In [39]:
# gives number of elements in an array
ar.size

9

In [40]:
# gives total bytes consumed by array
ar.nbytes

36

In [94]:
# 1D array
one = np.array([23,45,12,56,78])
one

array([23, 45, 12, 56, 78])

In [96]:
# returns the index where the max value is present in an array
one.argmax()

4

In [98]:
# returns the index where the min value is present in an array
one.argmin()

2

In [104]:
# returns how our array indexes should be for the array to be sorted
one.argsort()

array([2, 0, 1, 3, 4], dtype=int64)

In [108]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [110]:
ar.argmin()

0

In [112]:
ar.argmax()

8

In [116]:
# returns the indexes of elements by giving the max index in each column
ar.argmax(axis=0)

array([2, 2, 2], dtype=int64)

In [118]:
# returns the indexes of elements by giving the max index in each row
ar.argmax(axis=1)

array([2, 2, 2], dtype=int64)

In [120]:
ar.argsort(axis=0)

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]], dtype=int64)

In [122]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [124]:
# To create 1D array out of any array
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [128]:
# To reshape the array
ar.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [130]:
ar2 = np.array([[1,2,3],[1,3,2],[4,3,2]])
ar2

array([[1, 2, 3],
       [1, 3, 2],
       [4, 3, 2]])

In [134]:
# Addition of two numpy arrays it is not possible in normal lists
ar+ar2

array([[ 2,  4,  6],
       [ 5,  8,  8],
       [11, 11, 11]])

In [138]:
# Multiplication of two numpy arrays
ar*ar2

array([[ 1,  4,  9],
       [ 4, 15, 12],
       [28, 24, 18]])

In [142]:
# To take square root of each array element
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [144]:
ar.sum()

45

In [148]:
ar.max()

9

In [150]:
ar.min()

1

# To find elements in array


In [155]:
# gives the location where the array element is greater than 5
np.where(ar>5)

(array([1, 2, 2, 2], dtype=int64), array([2, 0, 1, 2], dtype=int64))

In [159]:
# returns the count of non zero elements
np.count_nonzero(ar)

9

In [163]:
# returns the tuple of indexes where the element is nonzero
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

In [165]:
ar[1,2] = 0

In [167]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 0, 1, 2], dtype=int64))

In [169]:
import sys

In [171]:
ch_ar = [0,4,55,2]

In [173]:
np_ar = np.array(ch_ar)

In [177]:
sys.getsizeof(1)*len(ch_ar)

112

In [179]:
np_ar.itemsize*np_ar.size

16

In [188]:
# returns list of numpy array
np_ar.tolist()

[0, 4, 55, 2]