In [1]:
import numpy as np

In [9]:
# Create a numpy array from a list
my_list = [1,2,3]
my_array = np.array(my_list)
my_array

array([1, 2, 3])

In [11]:
type(my_array)

numpy.ndarray

In [15]:
# Or from a list of list
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
arr = np.array(my_matrix)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
# Creating arrays using built-in functions
# Return evenly spaced values within a given interval
# start, stop, step
ar1 = np.arange(0,10)
ar1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
ar2 = np.arange(0,11,2)
ar2

array([ 0,  2,  4,  6,  8, 10])

In [25]:
# Generate arrays of zeros or ones
np.zeros(3)

array([0., 0., 0.])

In [31]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [33]:
np.ones(3)

array([1., 1., 1.])

In [35]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [37]:
# Return evenly spaced numbers over a specified interval
# start, stop, number of elements (and not step)
# Unlike numpy.arange(), the stop value is included in the result
# The spacing between values is automatically determined based on the 
#  specified number of values (num)
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [39]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [57]:
# Random number arrays
np.random.rand(23)

array([0.31713758, 0.73444668, 0.4035997 , 0.08134907, 0.82314649,
       0.97825783, 0.88727961, 0.68583007, 0.6699432 , 0.44433556,
       0.04937696, 0.76236195, 0.83655505, 0.59044211, 0.74736547,
       0.64625707, 0.53429523, 0.88092845, 0.1234031 , 0.94136271,
       0.06631304, 0.10064301, 0.38807577])

In [59]:
# Random number arrays
np.random.rand(5,5)

array([[0.952199  , 0.82231529, 0.32669725, 0.62257344, 0.09251518],
       [0.11452617, 0.52098528, 0.29223858, 0.51904211, 0.05216355],
       [0.1638539 , 0.75359229, 0.88641258, 0.77710239, 0.03093594],
       [0.88681639, 0.3280252 , 0.32906819, 0.95242592, 0.89091885],
       [0.69175878, 0.70497781, 0.41859721, 0.41029257, 0.21668394]])

In [61]:
# From normal distribution
np.random.randn(2)

array([ 0.78042754, -1.15804297])

In [63]:
np.random.randn(5,5)

array([[ 0.67173241,  0.08325399, -0.30774747, -0.52053241, -1.74021318],
       [-1.22167628, -1.02344719,  0.00370309, -1.83096302,  0.91914546],
       [-1.58097767, -0.19396689,  0.92164465, -2.12460007, -0.9546023 ],
       [ 1.72993406,  0.4967924 ,  0.6626892 , -2.11609607, -2.17983694],
       [ 0.14938047, -0.38651471,  0.91347809, -0.24105938,  0.0731315 ]])

In [69]:
# Random integers from low (inclusive) to high (exclusive)
# Single random integers between 1 and 100
np.random.randint(1,100)

64

In [71]:
# 10 random integers between 1 and 100
np.random.randint(1,100,10)

array([58, 46, 37,  6, 74, 26, 93, 91, 88, 43])

In [75]:
# Seeding for reproducable results
np.random.seed(77)
np.random.rand(4)  # 4 random numbers 

array([0.91910903, 0.6421956 , 0.75371223, 0.13931457])

In [81]:
np.random.seed(77)
np.random.rand(4)

array([0.91910903, 0.6421956 , 0.75371223, 0.13931457])

In [91]:
# Storing
arr = np.arange(25)  # numbers from 0 to 24
print(arr)
ranarr = np.random.randint(0,50,10)  # 10 random numbers between 0 and 50
print(ranarr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
[44 37 26 17 34 25  4 44 35  9]


In [93]:
# reshape: Returns an array containing the same data with a new shape
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [95]:
# Max, Min and their index positions
ranarr.max()

44

In [97]:
ranarr.min()

4

In [99]:
ranarr.argmax()

0